"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-08-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scholarship_alter_about_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='organisation_approved',
            field=models.BooleanField(default=False),
        ),
    ]