"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-09-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newsletterreceipients_delete_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterreceipients',
            name='newsletter',
        ),
    ]