"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-09-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_newsletterreceipients_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='media',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='sender',
        ),
    ]