"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-08-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_scholarshipapplicant_nursery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='created_date',
            field=models.DateField(),
        ),
    ]