"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_partners_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-end_date', 'start_date', 'title']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='eventtype',
            field=models.CharField(choices=[('seminar', 'Seminar'), ('fundraiser', 'Fundraiser'), ('donation', 'Donation'), ('awareness', 'Awareness'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('networking', 'Networking'), ('panel', 'Panel Discussion'), ('training', 'Training'), ('charity', 'Charity Event'), ('meetup', 'Meetup'), ('competition', 'Competition'), ('hackathon', 'Hackathon'), ('retreat', 'Retreat'), ('social', 'Social Event'), ('volunteering', 'Volunteering'), ('exhibition', 'Exhibition'), ('summit', 'Summit'), ('launch', 'Product Launch'), ('celebration', 'Celebration'), ('festival', 'Festival'), ('fundraising', 'Fundraising Event'), ('gala', 'Gala Dinner'), ('concert', 'Concert'), ('reunion', 'Reunion'), ('rally', 'Rally'), ('workshop', 'Workshop'), ('lecture', 'Lecture'), ('symposium', 'Symposium'), ('openhouse', 'Open House'), ('networking', 'Networking Event'), ('camp', 'Camp'), ('screening', 'Film Screening'), ('birthday', 'Birthday Party'), ('wedding', 'Wedding'), ('anniversary', 'Anniversary Celebration'), ('trade_show', 'Trade Show'), ('expo', 'Expo'), ('community', 'Community Event'), ('roundtable', 'Roundtable Discussion'), ('debate', 'Debate'), ('press_conference', 'Press Conference'), ('demonstration', 'Demonstration'), ('fund', 'Fundraising')], default='seminar', max_length=2555),
        ),
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='event',
            name='videos',
            field=models.JSONField(default=[]),
        ),
    ]