"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_options_rename_joined_date_user_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterreceipients',
            name='joined_at',
            field=models.DateTimeField(),
        ),
    ]