"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_options_remove_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='videos',
            field=models.JSONField(default=None),
        ),
    ]