"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-08-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_images_alter_event_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='images',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='event',
            name='videos',
        ),
    ]