"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-09-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_about_created_date_alter_about_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('founder', 'Founder'), ('co_founder', 'Co-Founder'), ('executive_director', 'Executive Director'), ('manager', 'Manager'), ('coordinator', 'Coordinator'), ('volunteer', 'Volunteer'), ('advisor', 'Advisor'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('communications_officer', 'Communications Officer'), ('development_officer', 'Development Officer'), ('program_director', 'Program Director'), ('event_planner', 'Event Planner')], default='Volunteer', max_length=2555),
        ),
    ]