"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-08-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_images_event_media_remove_event_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ongoing',
        ),
        migrations.AlterField(
            model_name='about',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]