"""Copyright (c) 2024 Esther Onyenoro

This software is licensed under [Proprietary License].
You may not modify, copy, or distribute this software without permission.
For more details, see the LICENSE file in the root of the repository."""

# Generated by Django 4.2.15 on 2024-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='achievements',
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='termsandconditions',
            field=models.CharField(default='Orphans and Children of the widows will be prioritized, Also the less priviledged children will be prioritized.', max_length=2555),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='termsandconditionsaccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('founder', 'Founder'), ('co_founder', 'Co-Founder'), ('executive_director', 'Executive Director'), ('manager', 'Manager'), ('coordinator', 'Coordinator'), ('member', 'Member'), ('advisor', 'Advisor'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('communications_officer', 'Communications Officer'), ('development_officer', 'Development Officer'), ('program_director', 'Program Director'), ('event_planner', 'Event Planner')], default='Volunteer', max_length=2555),
        ),
    ]