# Generated by Django 4.2.15 on 2024-12-19 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2555)),
                ('description', models.TextField()),
                ('participants', models.JSONField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('media', models.JSONField(default=None)),
            ],
            options={
                'ordering': ['-end_date', 'start_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
