# Generated by Django 5.0.1 on 2024-05-30 04:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('logo', models.TextField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('emailone', models.EmailField(max_length=255)),
                ('emailtwo', models.EmailField(blank=True, max_length=255, null=True)),
                ('emailthree', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('mission', models.TextField()),
                ('values', models.TextField()),
                ('achievements', models.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('branches', models.JSONField(null=True)),
                ('policies', models.TextField()),
                ('socials', models.JSONField()),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('seminar', 'Seminar'), ('fundraiser', 'Fundraiser'), ('donation', 'Donation'), ('awareness', 'Awareness')], max_length=255)),
                ('participants', models.JSONField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('ongoing', models.BooleanField(default=False)),
                ('images', models.ImageField(upload_to='events/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='events/')),
                ('docs', models.FileField(blank=True, null=True, upload_to='events/')),
            ],
            options={
                'ordering': ['-end_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='partners/')),
                ('link', models.URLField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date_paid', models.DateTimeField()),
                ('contributor', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='payments_receipts/')),
            ],
            options={
                'ordering': ['-date_paid', 'contributor', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-last_login', '-joined_date', 'firstname', 'lastname'],
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-date_created', 'user', 'action'],
            },
        ),
    ]
